[build]
  base = "frontend"
  command = "npm run build"
  publish = ".svelte-kit/output/client"
  functions = "../netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.environment]
  PYTHON_VERSION = "3.11"