[build]
  command = "python3 -m pip install --upgrade pip setuptools wheel && python3 -m pip install -r requirements.txt && cd frontend && npm install && npm run build"
  publish = "frontend/.svelte-kit/output/client"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11.3"